language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'browserify-seed' ]; then cd .. && eval "mv $currentfolder browserify-seed" && cd browserify-seed; fi
